title: Seixas Group
description: Showcase of our open-source materials projects
baseurl: ""
url: "https://seixasgroup.github.io"

plugins:
  - jekyll-remote-theme

remote_theme: thedevslot/WhatATheme


