title: Seixas Group
description: Showcase of our open-source materials projects
baseurl: ""
url: "https://seixasgroup.github.io"

# themes for jekyll: 
# - minima
# - jekyll-theme-cayman
# - jekyll-theme-slate
# - jekyll-theme-architect
# - jekyll-theme-dinky
# - jekyll-theme-leap-day
# - jekyll-theme-merlot
# - jekyll-theme-midnight
# - jekyll-theme-minimal
# - jekyll-theme-modernist
# - jekyll-theme-primer
theme: jekyll-theme-modernist


# plugins:
#   - jekyll-remote-theme

# remote_theme: thedevslot/WhatATheme


