title: Seixas Group
description: Showcase of our open-source materials projects
baseurl: ""                                 # because this *is* the user site
url: "https://seixasgroup.github.io"
theme: minima
